### ISSUE TITLE
How to add solvent parameter?

### ISSUE THREAD

**Issue by GiacomoDG96** [Andrew-S-Rosen/xtb_ase#60]
Hi, I would like to include acetonitrile solvent in my calculation.
In standard xtb you just add the command **–opt  --alpb acetonitrile /  --opt –-uhf 1 –chrg -1**
My code is:

atom_symbols, initial_coords = parse_coordinates(coordinates)
molecule = Atoms(symbols=atom_symbols, positions=initial_coords)
profile = XTBProfile(["xtb", "--opt"])
molecule.calc = XTB(profile=profile,method='gfn2-xtb', charge=1, uhf=1)
molecule.get_potential_energy()

In the documentation is not specified how to do it.
Someone has some suggestion?
Thank you in advance

**Comment by Andrew-S-Rosen** [comment]
Try

`XTBProfile(["xtb", "--opt", "--alpb", "acetonitrile"])`

for your profile.

**Comment by Andrew-S-Rosen** [comment]
Let me know if that does not work.

**Comment by GiacomoDG96** [comment]
Yes it works. Thank you so much @Andrew-S-Rosen
